# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: BorbosCI

on:
  push:
    branches: 
    - main_develop
    - main_test
  pull_request:
    branches:
    - main_develop
    - main_test
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Step 3 - Build with Maven
      run: mvn -B package --file SistemaBorbosBlock/pom.xml
          # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
          build: npm run build
          start: npm start
    - name: Jest run
      run: npm test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.37
